name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - run: pip install flake8
  - run: flake8 run.py core
 test:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    ubuntu:
     os: ubuntu-latest
     run-headless: python run.py -f=.github/examples/face.jpg -t=.github/examples/target.mp4 -o=.github/examples/output.mp4
     run-validate: ffmpeg -i .github/examples/snapshot.mp4 -i .github/examples/output.mp4 -filter_complex psnr -f null -
    windows:
     os: windows-latest
     run-headless: python run.py -f .github\examples\face.jpg -t .github\examples\target.mp4 -o .github\examples\output.mp4
     run-validate: ffmpeg -i .github\examples\snapshot.mp4 -i .github/examples\output.mp4 -filter_complex psnr -f null -
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up ffmpeg
    uses: FedericoCarboni/setup-ffmpeg@v2
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
     python-version: 3.9
  - run: pip install -r requirements.txt gdown
  - run: gdown 13QpWFWJ37EB-nHrEOY64CEtQWY-tz7DZ
  - run: ${{ matrix.run-headless }}
  - run: ${{ matrix.run-validate }}

